---
- name: Install Certbot Repo
  apt_repository:
    repo: "ppa:certbot/certbot"
    state: present
    update_cache: yes

- name: Install Certbot
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - certbot
    - python-certbot-nginx 
